# Generated by Django 4.0.6 on 2022-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.IntegerField(default=1),
        ),
    ]
